#Project
mod_version=21.11-b1.1
project_group=net.rebel459.unified

#Mod
mod_author=Rebel459
mod_id=unified
mod_name=Unified API

# Shared
minecraft_version=1.21.11

# NeoForge
fabric_loader=0.18.4
fabric_api=0.141.3+1.21.11

# NeoForge
neoforge_version=9-beta

# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false