#Project
mod_version=26.1-snapshot-7-b1.0
project_group=net.rebel459.unified

#Mod
mod_author=Rebel459
mod_id=unified
mod_name=Unified API

# Shared
minecraft_version=26.1-snapshot-7

# NeoForge
fabric_loader=0.18.4
fabric_api=0.143.4+26.1

# NeoForge
neoforge_version=net.neoforged:neoforge:26.1.0.0-alpha.12+snapshot-7

# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false